config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  scope "/:locale" do
    get '/news', to: 'news#index', as: 'news'
    get '/archive', to: 'archive#index', as: 'archive'
  end

  root 'home#index'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_rich_text :content
end

app/models/publication.rb
class Publication < ApplicationRecord
  has_many :publication_headers
  has_one_attached :pdf_file

  validates :title, presence: true
  validates :number, presence: true
  validates :subtitle, presence: true
  validates :distribution_date, presence: true
  validates :pdf_file, presence: true
  validate :validate_pdf_file_type

  private

  def validate_pdf_file_type
    if pdf_file.attached? && !pdf_file.content_type.in?(%w(application/pdf))
      errors.add(:pdf_file, I18n.t('activerecord.errors.models.publication.attributes.pdf_file.content_type'))
    end
  end
end

app/models/publication_header.rb
class PublicationHeader < ApplicationRecord
  belongs_to :publication
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/HomeController.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/admin/base_controller.rb
# frozen_string_literal: true
class Admin::BaseController < ActionController::Base
  around_action :use_default_locale

  private

  def use_default_locale(&block)
    # Executes the request with the I18n.default_locale.
    # https://github.com/ruby-i18n/i18n/commit/9b14943d5e814723296cd501283d9343985fca4e
    I18n.with_locale(I18n.default_locale, &block)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || session[:locale] || I18n.default_locale
  end
end

app/controllers/archive_controller.rb
# frozen_string_literal: true
class ArchiveController < ApplicationController
  def index
    @publications = Publication.includes(:publication_headers).order(distribution_date: :desc).page(params[:page]).per(5)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/news_controller.rb
# frozen_string_literal: true
class NewsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def available_locales
    I18n.available_locales
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/archive/index.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag 'archive_index' %>
<% end %>

<% @publications.group_by { |publication| publication.distribution_date.year }.each do |year, publications| %>
  <div class="row">
    <div class="row">
      <% min_publication = publications.min_by { |publication| publication.number } %>
      <p class="publication_group_header"><%=t('publication.group_header', year: year, number: min_publication.number) %></p>
    </div>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% publications.each do |publication| %>
        <div class="col">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= publication.title %></h5>
              <p class="card-text"><%= publication.subtitle %></p>
            </div>
            <ul class="list-group list-group-flush">
              <% publication.publication_headers.each do |header| %>
                <li class="list-group-item"><%= header.content %></li>
              <% end %>
            </ul>
            <div class="card-footer text-body-secondary">
              <%= link_to t('publication.download'), rails_blob_path(publication.pdf_file, disposition: 'attachment') %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
<% end %>
<div class="row pt-5">
  <div class="col">
    <%= paginate @publications, theme: 'bootstrap-5' %>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('application.title') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', "data-turbo-track": "reload" %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <header>
      <%= render 'shared/navbar' %>
      <%= render "shared/flash" %>
    </header>
    <main role="main" class="container">
      <%= yield %>
    </main>
    <footer class="sticky-bottom">

    </footer>
  </body>
</html>

app/views/shared/_flash.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
      document.addEventListener('DOMContentLoaded', function () {
        <% flash.each do |msg_type, msg| %>
          toastr['<%= msg_type.gsub(/alert|notice/, 'alert' => 'error', 'notice' => 'info') %>']('<%= msg %>');
      <% end %>
      });
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_pack_tag("baytown_news_logo.jpeg", alt: "幕張ベイタウンニュース", width: 30, height: 24) %>
    Makuhari Baytown News
  <% end %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to t('navbar.menu.news'), news_path(locale: locale), class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('navbar.menu.archive'), archive_path(locale: locale), class: 'nav-link' %>
      </li>
    </ul>

    <ul class="navbar-nav px-2">
      <li class="nav-item dropstart">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= t('navbar.language') %>
        </a>
        <ul class="dropdown-menu">
          <%= form_tag(url_for(locale: params[:locale]), method: :get) do %>
            <% available_locales.each do |locale| %>
              <li><%= link_to t("languages.#{locale}"), { locale: locale }, class: 'dropdown-item', method: :get %></li>
            <% end %>
          <% end %>
        </ul>
      </li>
    </ul>
  </div>
</nav>